# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-PT-Speaker
version:      0.06
version_from: lib/Lingua/PT/Speaker.pm
installdirs:  site
requires:
    Config::AutoConf:              0.03
    Lingua::PT::PLN:               0.05
    Text::RewriteRules:            0.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
