---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-PT-Speaker
no_index:
  directory:
    - t
    - inc
requires:
  Lingua::PT::PLN: 0.05
  Text::RewriteRules: 0.09
version: 0.11
